"""Fail-closed selection and honest limited-diagnostic reporting controls."""
import contextlib
import io
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from tools.gdl.composed_census import r67_runtime_allsource_probe as probe
from tools.gdl.composed_census import r67_runtime_visibility_probe as visibility


class AllSourceSelectionTests(unittest.TestCase):
    def units(self):
        return [
            dict(linked_object="src/exact.o", source_object="src/exact.o", configured=True,
                 configured_completed=True, linkage="source", autogenerated=False),
            dict(linked_object="obj/open.o", source_object="src/open.o", configured=True,
                 configured_completed=False, linkage="extracted_fallback", autogenerated=False),
            dict(linked_object="obj/auto_data.o", source_object=None, configured=False,
                 configured_completed=False, linkage="extracted_fallback", autogenerated=True),
        ]

    def select(self, units):
        return probe.select_inputs(units, [u["linked_object"] for u in units])

    def test_exact_source_and_auto_data_are_retained(self):
        units = self.units()
        selected, replacement = self.select(units)
        self.assertEqual(selected, [units[1]])
        self.assertEqual(replacement, {"obj/open.o": "src/open.o"})
        self.assertEqual([replacement.get(u["linked_object"], u["linked_object"]) for u in units],
                         ["src/exact.o", "src/open.o", "obj/auto_data.o"])

    def test_order_mismatch_refuses(self):
        units = self.units()
        with self.assertRaisesRegex(ValueError, "ordered"):
            probe.select_inputs(units, [u["linked_object"] for u in reversed(units)])

    def test_missing_source_and_auto_source_and_already_linked_refuse(self):
        for key, value in (("source_object", None), ("autogenerated", True), ("linkage", "source")):
            with self.subTest(key=key):
                units = self.units()
                units[1][key] = value
                with self.assertRaisesRegex(ValueError, "well defined"):
                    self.select(units)

    def test_empty_or_duplicate_substitution_set_refuses(self):
        with self.assertRaisesRegex(ValueError, "nonempty"):
            self.select([self.units()[0]])
        units = self.units()
        units.append(dict(units[1]))
        with self.assertRaisesRegex(ValueError, "duplicate extracted"):
            self.select(units)


class VisibilityProbeTests(unittest.TestCase):
    def source(self):
        return b"\r\n".join(b"static void " + name.encode() + suffix
                            for name in visibility.HELPERS for suffix in (b"(void);", b"(void) { BODY; }"))

    def test_removes_exactly_six_tokens_and_preserves_bodies_and_line_endings(self):
        source = self.source()
        active, forms = visibility.source_forms(source)
        self.assertEqual(active, "static")
        self.assertEqual(forms["static"], source)
        result = forms["global"]
        self.assertEqual(result, source.replace(b"static ", b""))
        self.assertEqual(result.count(b"BODY"), 3)
        self.assertEqual(result.count(b"\r\n"), 5)
        self.assertEqual(len(source) - len(result), 6 * len(b"static "))

    def test_missing_or_additional_declaration_refuses(self):
        for source in (self.source().replace(b"mbInitBlitEntry(void);", b"different(void);"),
                       self.source() + b"\nstatic void mbInitBlitEntry(void);\n"):
            with self.assertRaisesRegex(ValueError, "exactly one"):
                visibility.source_forms(source)

    def test_global_active_form_reconstructs_identical_static_control(self):
        source = self.source().replace(b"static ", b"")
        active, forms = visibility.source_forms(source)
        self.assertEqual(active, "global")
        self.assertEqual(forms["global"], source)
        self.assertEqual(forms["static"], self.source())

    def test_mixed_state_or_two_declarations_refuse(self):
        with self.assertRaisesRegex(ValueError, "mixed"):
            visibility.source_forms(self.source().replace(b"static ", b"", 1))
        with self.assertRaisesRegex(ValueError, "exactly one"):
            visibility.source_forms(self.source().replace(b"{ BODY; }", b";"))


class AllSourceDiagnosticTests(unittest.TestCase):
    def test_repeat_diagnostics_are_not_unique_symbol_counts(self):
        result = probe.diagnostic_summary("undefined: 'helper'\nundefined: 'helper'\n"
                                          "multiply-defined: 'data'\nError: too many link errors\n")
        self.assertEqual(result["undefined_diagnostics"], 2)
        self.assertEqual(result["undefined_symbols"], ["helper"])
        self.assertEqual(result["multiply_defined_diagnostics"], 1)
        self.assertTrue(result["truncated_by_error_limit"])

    def test_success_has_no_errors_and_does_not_claim_truncation(self):
        result = probe.diagnostic_summary("")
        self.assertEqual(result["undefined_diagnostics"], 0)
        self.assertEqual(result["multiply_defined_symbols"], [])
        self.assertFalse(result["truncated_by_error_limit"])

    def test_stale_or_matching_graph_refuses_before_any_link(self):
        for stale in (True, False):
            with self.subTest(stale=stale), tempfile.TemporaryDirectory() as td:
                root = Path(td)
                (root / "build/GUNE5D").mkdir(parents=True)
                (root / "build.ninja").write_bytes(b"current")
                snapshot = dict(schema_version=1, ninja_sha256="stale" if stale else probe.digest(root / "build.ninja"),
                                non_matching=False)
                (root / "build/GUNE5D/build_edges.json").write_text(json.dumps(snapshot))
                output = root / "build/r67_runtime_refusal.json"
                with patch.object(probe, "ROOT", root), patch.object(probe.os, "name", "nt"), \
                     patch.object(probe, "run", side_effect=AssertionError("must not launch")), \
                     contextlib.redirect_stdout(io.StringIO()):
                    self.assertEqual(probe.main(["--out", str(output)]), 2)
                result = json.loads(output.read_text())
                self.assertEqual(result["status"], "UNRESOLVED")
                self.assertIn("stale" if stale else "--non-matching", result["error"])

    def test_output_cannot_overwrite_production_or_source(self):
        for output in (str(probe.ROOT / "configure.py"), str(probe.ROOT / "build/GUNE5D/main.elf")):
            with self.subTest(output=output), contextlib.redirect_stderr(io.StringIO()):
                with self.assertRaises(SystemExit) as raised:
                    probe.main(["--out", output])
                self.assertEqual(raised.exception.code, 2)


if __name__ == "__main__":
    unittest.main()
