"""Bounded editable-mode link experiment using all configured source objects.

First run configure.py --non-matching and ninja -j2 all_source, then this tool.
It reproduces the actual normal link in a unique build/ directory, verifies
the ELF equals the production control, and substitutes only the configured
unfinished TUs for a second scratch link. Auto data/BSS objects are retained
and counted explicitly. It never changes source, configuration or production
link outputs. PASS means the experiment completed, not that the trial linked.
Repeat --unit to substitute only named unfinished TUs, keeping every other
actual input unchanged. A selected-unit trial is never labelled all-source.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[3]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def diagnostic_summary(output):
    duplicates = re.findall(r"multiply-defined: '([^']+)'", output)
    undefined = re.findall(r"undefined: '([^']+)'", output)
    return {"multiply_defined_diagnostics": len(duplicates),
            "multiply_defined_symbols": sorted(set(duplicates)),
            "undefined_diagnostics": len(undefined), "undefined_symbols": sorted(set(undefined)),
            "truncated_by_error_limit": "too many link errors" in output}


def unit_key(name):
    return re.sub(r"\.(?:cpp|c|s)$", "", name.replace("\\", "/").removeprefix("src/"))


def select_inputs(units, linked_inputs, requested_units=None):
    """Reconcile ordered configured sources without dropping automatic data."""
    if [u["linked_object"] for u in units] != linked_inputs:
        raise ValueError("unit inventory does not reconcile exact ordered linker inputs")
    substitutions = [u for u in units if u["configured"] and not u["configured_completed"]]
    if not substitutions or any(not u["source_object"] or u["linkage"] != "extracted_fallback"
                                or u["autogenerated"] for u in substitutions):
        raise ValueError("nonempty unfinished source substitution set is not well defined")
    if requested_units is not None:
        requested = [unit_key(name) for name in requested_units]
        if not requested or len(requested) != len(set(requested)):
            raise ValueError("selected-unit list is empty or repeats a unit")
        eligible = [unit_key(u["name"]) for u in substitutions]
        if len(eligible) != len(set(eligible)):
            raise ValueError("unfinished unit names are ambiguous")
        missing = sorted(set(requested) - set(eligible))
        if missing:
            raise ValueError("selected units are not configured unfinished sources: " + ", ".join(missing))
        substitutions = [u for u in substitutions if unit_key(u["name"]) in requested]
    replace = {u["linked_object"]: u["source_object"] for u in substitutions}
    if len(replace) != len(substitutions):
        raise ValueError("duplicate extracted input in substitutions")
    return substitutions, replace


def run(argv):
    result = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True, errors="replace", timeout=90)
    return {"argv": argv, "exit_code": result.returncode,
            "stdout": result.stdout, "stderr": result.stderr}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("build/r67_runtime_allsource.json"))
    parser.add_argument("--max-errors", type=int, choices=(1000,),
                        help="pass the locally documented diagnostic-only -maxerrors 1000 to both control and trial")
    parser.add_argument("--unit", action="append", help="exact unfinished unit to substitute; repeat for a subset (default: all)")
    args = parser.parse_args(argv)
    output = args.out.resolve()
    if (not output.is_relative_to((ROOT / "build").resolve()) or output.suffix != ".json"
            or not output.name.startswith("r67_runtime_")):
        parser.error("--out must name r67_runtime_*.json under this checkout's build/")
    result = {"schema_version": 1, "status": "UNRESOLVED", "scope": __doc__}
    try:
        if os.name != "nt":
            raise ValueError("this bounded actual-command probe currently supports native Windows only")
        snap_path = ROOT / "build/GUNE5D/build_edges.json"
        snapshot = json.loads(snap_path.read_text())
        if snapshot.get("schema_version") != 1 or snapshot.get("ninja_sha256") != digest(ROOT / "build.ninja"):
            raise ValueError("active build snapshot is absent, unsupported or stale")
        if snapshot.get("non_matching") is not True:
            raise ValueError("configure.py --non-matching first; the trial requires untouched editable objects")
        pending = run(["ninja", "-n", "all_source"])
        if pending["exit_code"] or pending["stdout"].strip() != "ninja: no work to do.":
            result["pending"] = pending
            raise ValueError("ninja all_source is not up to date; build it before measuring")
        links = [e for e in snapshot["edges"] if e["rule"] == "link"]
        if len(links) != 1 or links[0]["outputs"] != ["build/GUNE5D/main.elf"]:
            raise ValueError("expected one default DOL ELF link")
        link = links[0]
        units = snapshot["units"]
        substitutions, replace = select_inputs(units, link["inputs"], args.unit)
        compdb_result = run(["ninja", "-t", "compdb", "link"])
        if compdb_result["exit_code"]:
            raise ValueError("ninja compdb failed")
        compdb = json.loads(compdb_result["stdout"])
        if len(compdb) != 1:
            raise ValueError("link command is not unique")
        command = compdb[0]["command"]
        tokens = [token.strip('"') for token in shlex.split(command, posix=False)]
        if not tokens or not tokens[0].lower().endswith("mwldeppc.exe") or tokens.count("-o") != 1:
            raise ValueError("unsupported actual linker command")
        if any(token in {"-map", "&&", ";", "|", ">"} for token in tokens):
            raise ValueError("command has unsupported extra output or shell operation")
        oi = tokens.index("-o") + 1
        ri = [i for i, token in enumerate(tokens) if token.startswith("@")]
        if len(ri) != 1 or tokens[oi].replace("\\", "/") != link["outputs"][0]:
            raise ValueError("unexpected output/response-file argument")
        paths = {ROOT / p for p in link["inputs"] + list(replace.values())}
        paths.update({snap_path, ROOT / "build.ninja", ROOT / "configure.py",
                      ROOT / "build/GUNE5D/ldscript.lcf", ROOT / "build/GUNE5D/main.elf",
                      ROOT / "build/GUNE5D/main.dol", ROOT / tokens[0]})
        protected = {str(p.relative_to(ROOT)): digest(p) for p in paths}
        folder = Path(tempfile.mkdtemp(prefix="r67_runtime_allsource_", dir=ROOT / "build"))
        result.update(artifacts=str(folder.relative_to(ROOT)), actual_link_command=command,
                      max_errors=args.max_errors,
                      substitution_scope="selected_units" if args.unit is not None else "all_configured_source",
                      requested_units=args.unit,
                      substitutions=substitutions, protected_before=protected,
                      input_count=len(units), original_source_inputs=sum(u["linkage"] == "source" for u in units),
                      substituted_source_inputs=len(substitutions),
                      final_source_inputs=sum(u["linkage"] == "source" for u in units) + len(substitutions),
                      remaining_extracted_inputs=sum(u["linkage"] == "extracted_fallback" for u in units) - len(substitutions),
                      autogenerated_inputs=sum(u["autogenerated"] for u in units))
        result["links"] = {}
        trial_label = "selected_configured_source" if args.unit is not None else "all_configured_source"
        result["trial_label"] = trial_label
        for label, inputs in (("control", link["inputs"]),
                              (trial_label, [replace.get(p, p) for p in link["inputs"]])):
            dest, response = folder / (label + ".elf"), folder / (label + ".rsp")
            response.write_text("\n".join('"' + p + '"' for p in inputs) + "\n", encoding="ascii")
            link_argv = list(tokens)
            link_argv[oi] = str(dest.relative_to(ROOT))
            link_argv[ri[0]] = "@" + str(response.relative_to(ROOT))
            if args.max_errors:
                link_argv.extend(["-maxerrors", str(args.max_errors)])
            observation = run(link_argv)
            observation["response_file"] = str(response.relative_to(ROOT))
            observation["response_sha256"] = digest(response)
            observation["ordered_inputs"] = inputs
            observation["output_sha256"] = digest(dest) if dest.is_file() else None
            observation["diagnostics"] = diagnostic_summary(observation["stdout"] + observation["stderr"])
            result["links"][label] = observation
            if label == "control" and (observation["exit_code"] or observation["output_sha256"] != digest(ROOT / "build/GUNE5D/main.elf")):
                raise ValueError("scratch unchanged link did not reproduce production ELF exactly")
        result["protected_unchanged"] = protected == {str(p.relative_to(ROOT)): digest(p) for p in paths}
        if not result["protected_unchanged"]:
            raise ValueError("a protected production input/output changed during the scratch experiment")
        result["status"] = "PASS"
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as error:
        result["error"] = str(error)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(result["status"], result.get("error", "bounded link experiment completed"), output)
    if "links" in result:
        for label, observation in result["links"].items():
            print(label, "exit", observation["exit_code"], "ELF", observation["output_sha256"])
            if observation["exit_code"]:
                print(observation["stdout"] + observation["stderr"])
    return 0 if result["status"] == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
